### ISSUE TITLE
Top Level Cookie domains

### ISSUE THREAD

**Issue by robertpitt** [astronomerio/meteor-astronomer#17]
Hey guys,

We have run into some data issues on mixpanel where were getting records from our QA layer in our production app.

We have deduced the cause of the issue to be conflicting cookie data.

We have tghe following domains:

qa.domain.com
pr.domain.com

If we visit qa.domain.com we get a cookie which is being set to *.domain.com, and then when we go ro pr.domain.com that cookie is read and sent to our production mixpanel.

Doing a little digging we found that your choice of setting cookies on all somdomains has caused this issue.

https://github.com/astronomerio/meteor-astronomer/blob/c506530894a8874de0811272f1933b87d6a901c6/lib/analytics.js/analytics.js#L3515

Is there a possibility to make this configurable some how so we can avoid these sorts of conflicts.

Cheers.

@robfallows @peterchoo

**Comment by schnie** [comment]
Hey guys, we are actually in the middle of some changes that could potentially make this easier depending on a couple of things.  There are a couple of ways to handle it and I need to think it through a little more.

Until then, in some top level meteor code, you could run something like this to manually set the cookie domain, which could come from meteor settings or some other environment specific source:

`analytics._options(_.extend(analytics.options, {cookie: {domain: 'qa.domain.com'}}));`

It just calls the `_options` method passing in any currently set options (possibly just an empty object) and adds the cookie options, specifically the domain object.  Any cookie operations going forward should use the new settings.

I'll report back when we have a better way to do this!

**Comment by robertpitt** [comment]
Hey guys, any update on your changes to this.

Regards.

**Comment by robertpitt** [comment]
Sorry I did not mention, the fix does not seem to work as where your setting the cookie your not even using the options, seems your enforcing a call for `topDomain`.. If you need me to dig through to find the code causing the issue lmk.

**Comment by schnie** [comment]
Hey @robertpitt, I see what you mean.  How are you guys set up on astronomer?  Do you have a separate astronomer app for qa and prod?  One option could be to just not provide an astronomer appId in your qa environment, preventing the plugin from doing anything at all.

**Comment by robertpitt** [comment]
Yea we discussed that solution as a final resort if we could not get both systems to work in parallel, would it still be feasible for you guys to do a bug fix as the options for cookies are currently pointless if you cannot configure them correctly.

Thanks for your response.

**Comment by schnie** [comment]
Hmm, looking again, I think it should work.  It should end up using the value passed in as options.domain.  It's using https://github.com/avetisk/defaults for the `defaults` function.  So after assigning `this._options` to the result of calling `defaults`, `this._options.domain` should actually be whatever was passed in, since it would not evaluate to `undefined` and be populated with the default value instead.

This library actually downloads mixpanels library and uses it, so maybe the problem could be there.

Are you guys on the latest version of the meteor package?

**Comment by robertpitt** [comment]
From what I have been told the options are set but not obeyed by the analytics.js, please see ( https://github.com/astronomerio/analytics.js/blob/master/analytics.js#L3525 )

You can see what topDomain is alsways being called and assigned to domain, and domin property is in the second object in extend, meaning it will overwrite.

@peterchoo looked at this issue for us.

**Comment by peterchoo** [comment]
Hi,

We are currently wrapping Astronomer in a local package, as we do with all external dependencies so that we can configure them.  We have seen several different weird behaviours when attempted to apply this fix.

Initially we were still on 0.2.16, and we had the following:

```js
Package.onUse(function(api) {
  api.versionsFrom('1.0.5');
  /**
   * Add dependecies
   */
  api.use([
    "underscore"
  ]);
  /**
   * Include the patch to fix top level domain issues
   * https://github.com/astronomerio/meteor-astronomer/issues/17
   */
  api.addFiles([
    'pollutionfix.js'
  ], 'client');

  api.use("astronomerio:core@0.2.16");
});
```

Where pollutionfix.js is:
```js
Meteor.startup(function() {
  if (Meteor.settings.public.domain) {
    analytics._options(_.extend({}, analytics.options, {
      cookie: {
        domain: Meteor.settings.public.domain
      }
    }));
  }
});
```

This would set `analytics.options.cookie.domain` along with the other defaults, but the cookies would still be using the top level domain:

![astro1](https://cloud.githubusercontent.com/assets/5271469/12292941/33a9846a-b9e8-11e5-8dd5-4cd787212528.png)

If I then log out and back in I get the following:

![2](https://cloud.githubusercontent.com/assets/5271469/12292959/44f71aca-b9e8-11e5-8930-779bf17af530.png)

Following this, when I upgrade to 0.2.19, with the same code (and a `console.log(_.clone(analytics))` statement before the erroring line) I get this:

![3](https://cloud.githubusercontent.com/assets/5271469/12293038/c73857ec-b9e8-11e5-9277-5cbfd11af667.png)

This has added a new mixpanel cookie using the correct subdomain (which looks like encoded json), but the astronomer ones are not using the options provided.  Moving the `api.use("astronomerio:core@0.2.19");` line above the `api.addFiles` for `pollutionfix.js` makes no difference.

Hope this helps us come to a solution for this, thanks!

**Comment by schnie** [comment]
Ah, I see.  I think the call to `analytics._options` may be happening too late, after the cookies have already been set.  It looks like the correct way to do it would be to pass the options to the `Analytics` constructor.  This is currently happening in the built javascript file that the package downloads asynchronously.  We build a custom version of `analytics.js` for each appId, and that is where a cookie subdomain would need to be passed in.

I think at this time, your best option would be to just not include an astronomer appId in your QA environment (disabling astronomer), or creating a separate app in astronomer and using that.

**Comment by peterchoo** [comment]
Thanks for confirming that for us, we will discuss whether we need qa data right now and take it from there.
